#spring:
#  datasource:
#    password: 1234
#    url: jdbc:h2:mem:db
#    username: sa

    
spring:
#  profiles:
#    active:
#    - mysql
  batch:
    job:
      enabled: false
  application:
    name: ecommerce    
  datasource:
   # driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost/ecommerce?useTimezone=true&serverTimezone=UTC
    username: root
    hikari:
      maximum-pool-size: ${ENV_DB_MAX_CON:60}
      minimum-idle: ${ENV_DB_MIN_IDLE:0}
      idle-timeout: ${ENV_DB_IDLE_TIMEOUT:180000}
  jpa:
   # database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        type: trace
        use_sql_comments: true
        
application:
  async:
    corePoolSize: ${ENV_THREAD_COREPOOLSIZE:10}
    maxPoolSize: ${ENV_THREAD_MAXPOOLSIZE:20}
    queueCapacity: ${ENV_THREAD_QUEUECAPACITY:30}
    
logging:
  level:
    root: info
    org.springframework.web: info
    com.howtodoinjava: info
    org.hibernate: info
